server:
  port: 9001
spring:
  application:
    name: eureka-producer
  security:
        basic:
          enable: true #开启基于HTTP basic的认证
        user: #配置用户的账号信息
          name: admin
          password: 123456
eureka:
  instance:
    #注册中心地址
    hostname: 127.0.0.1
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://${spring.security.user.name}:${spring.security.user.password}@${eureka.instance.hostname}:10001/eureka/
