spring:
  application:
    name: eureka-server
  security:
      basic:
        enable: true #开启基于HTTP basic的认证
      user: #配置用户的账号信息
        name: admin
        password: 123456
eureka:
  instance:
    hostname: peer1

  client:
    #是否将该实例信息注册到其他eureka server上；如果设置为false，那么该server无法被其他server发现，但是仍然可以发现其他server
    registerWithEureka: true
    #是否允许该客户端从eureka server上获取注册信息
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://${spring.security.user.name}:${spring.security.user.password}@peer2:10002/eureka/,http://${spring.security.user.name}:${spring.security.user.password}@peer3:10003/eureka/
  server:
      enable-self-preservation: false #禁用自我保护模式
server:
  port: 10001